# Generated by Django 5.1.1 on 2024-10-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="transferred",
        ),
        migrations.AlterField(
            model_name="review",
            name="feedback",
            field=models.TextField(default=""),
        ),
    ]
