# Generated by Django 5.1.1 on 2024-10-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_article_bookmark_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="full_content",
            field=models.BinaryField(),
        ),
    ]
