# Generated by Django 5.1.1 on 2024-10-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_article_transferred_alter_review_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="content",
        ),
        migrations.AddField(
            model_name="article",
            name="transferred",
            field=models.BooleanField(default=False),
        ),
    ]
