# Generated by Django 5.1.1 on 2024-10-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_article_full_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="url_to_image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
