# Generated by Django 5.1.1 on 2024-10-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_article_url_alter_article_url_to_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="full_content",
            field=models.TextField(),
        ),
    ]
