# Generated by Django 5.1.1 on 2024-10-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_useractivitylogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylogs",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
